---
title       : Developing Data Products Project 3 - Shiny Application & Reproducible Pitch
subtitle    : September 10, 2020
author      : Philip Barker
job         : 
framework   : io2012    # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

# Purpose

The purpose of this assignment is to create a visualization of some data in the Shiny application and upload it to a webpage. This presentation will serve to explain the purpose of the application.

I was originally going to include a regression model, but due to technical issues I was unable to get it to display properly. I surmise it has to do with the unusual nature of the data.

--- 
# The Application

The Shiny application I created charts the COVID virus data by country versus the total population. It allows the user to enter the date and select the ratio for charting the overall case spread. There is also plotly support so the user can mouseover to see more details, as well as zoom in.

---
# Links
<br>

### [You can see the app here](https://pabarker.shinyapps.io/covidvis/)
<br>
<br>
### [Here is the link to the source code](https://github.com/PlaceholderPigone/DevelopingDataProductsProject3)

---
# Thank You

